### ISSUE TITLE
Code-signing issue

### ISSUE THREAD

**Issue by JayBrown** [nark/WiredClient#113]
The file **default_chat.css** in the Wired.app bundle (debug version) was modified after code-signing.

```
~/Applications/Wired Client.app: a sealed resource is missing or invalid
file modified:
~/Applications/Wired Client.app/Contents/Resources/Templates/Neo.WiredTemplate/Contents/Resources/htdocs/css/default_chat.css
```

This can lead to problems, e.g. I'm getting constant prompts by DeepGuard (f.k.a. X-FENCE f.k.a. Little Flocker) to allow file access for Wired.

**Comment by nark** [comment]
Hey,

Thank you for report. It confirms my latest thoughts that the theme/template implementation has to be dropped for something else.

However, we are not talking about Wired.app (which is the Swift app), but Wired Client.app here.

**Comment by JayBrown** [comment]
Right, I'm using the "legacy" Wired Client (latest release, debug version).

**Comment by JayBrown** [comment]
With build 58 it's two modified files now:

default_messages.css
default_boards.css

However, when I **re-codesign** the Wired Client bundle, everything's fine, no file access errors etc.

So you probably just need to do the last code-signing run at the very end, *after* you have edited the css files. It doesn't need to be a `--deep` code-signing, because the stuff in question is in the `Resources` folder anyway, so it will just be written into the `CodeResources`, and never signed *as code proper*.

**Comment by nark** [comment]
Ok thank you. Anyway, I'm dropping the current template system in favour of an auto-layout based UI. Important changes are coming in 2.6 to fix these issues.
