### ISSUE TITLE
Can't UPload _from_ NTFS volumes

### ISSUE THREAD

**Issue by bart0li** [nark/WiredClient#59]
To reproduce: Mount an NTFS volume on the client machine and try to upload a file FROM there. The transfer fails with an error message "The operation could not be completed. No such file or directory".

**Comment by beren12** [comment]
This also fails with network shares.

**Comment by sc1sm3** [comment]
Is it possible for you to check if this issue is solved in the latest build?
It could be related to the bug with uploading from an APFS-formatted filesystem we had and since that works now, this could too!

**Comment by nark** [comment]
Yes, both issues could be related. I can't check right now, but it's easy to do : format an USB key as FAT or ExFAT and try to upload a file stored into it.
