### ISSUE TITLE
Upload fails

### ISSUE THREAD

**Issue by olind** [nark/WiredClient#81]
Not sure if this is a bug in the Unix server (running on OSX 10.13.6) or in the client. Sorry.

I've just set up a new server and download works. When I try to upload files it gives me the following error. I've tried to give full permissions to upload folder but i doesn't help. 

The file is created in the folder but it's an empty file with the .WiredTransfer file extension.

![nosuchfile](https://user-images.githubusercontent.com/122699/46850161-12be2b80-cdf3-11e8-9291-c925df49d2bf.png)

**Comment by olind** [comment]
I did just test an upload to the Wired dev server and it didn't work there either. I guess that means it something wrong with the client (and not my server)?

**Comment by sc1sm3** [comment]
This should be fixed in the latest builds. It's a bug that relates to APFS (and possibly also other filesystems).

**Comment by olind** [comment]
I'm pretty sure I used WiredClient-2.1.1-310 from SourceForge. Is that the latest?

**Comment by sc1sm3** [comment]
There should be a newer debug build here: https://github.com/nark/WiredClient/releases
